apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/order-db"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:3000"