version: '3'
services:
  product-service:
    build: ./product
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/product-db
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: